routes/web.php
<?php

use App\Http\Controllers\User\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});

Route::resource('users', UserController::class);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/User/UserController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Http\Requests\Users\{UserCreateRequest, UserUpdateRequest};
use App\Models\User;

class UserController extends Controller
{
    public const TEMPLATE_PATH = 'users.';

    public function index()
    {
        $with = [
            'users' => User::get(),
            'title' => __('user.index.title'),
        ];
        return view(self::TEMPLATE_PATH . __FUNCTION__)->with($with);
    }

    public function create()
    {
        $with = [
            'title' => __('user.create.title'),
        ];
        return view(self::TEMPLATE_PATH . __FUNCTION__)->with($with);
    }

    public function store(UserCreateRequest $request)
    {
        User::create($request->toArray());

        return redirect(route('users.index'));
    }

    public function show(User $user)
    {
        $with = [
            'user' => $user,
            'title' => __('user.show.title'),
        ];
        return view(self::TEMPLATE_PATH . __FUNCTION__)->with($with);
    }

    public function edit(User $user)
    {
        $with = [
            'user' => $user,
            'title' => __('user.edit.title'),
        ];
        return view(self::TEMPLATE_PATH . __FUNCTION__)->with($with);
    }

    public function update(UserUpdateRequest $request, User $user)
    {
        $user->update($request->toArray());

        return redirect(route('users.index'));
    }

    public function destroy($id)
    {
        $user = User::FindOrFail($id);
        $user->delete();

        return response()->json(['status' => 'success']);
    }
}

resources/views/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
</head>

<body>

@include('navbar')

@yield('content')
<script src = "https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
<script src="{{ asset('main.js') }}"></script>
</body>
</html>

resources/views/navbar.blade.php
<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse mb-4">
    <button class="navbar-toggler navbar-toggler-right" type="button"
            data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{{ route('users.index') }}">{{__('navbar.all_users')}}</a>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
        </ul>
        <form class="form-inline mt-2 mt-md-0">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ route('users.create') }}"> {{__('navbar.create_user')}}
                        <span class="sr-only"></span>
                    </a>
                </li>
            </ul>
        </form>
    </div>
</nav>

resources/views/users/create.blade.php
@extends('master')
@section('content')
    <div class="container">
        <form action="{{ route('users.store') }}" method="POST">
            {{ csrf_field() }}
            <div class="form-group">
                <label for="exampleInputName">{{ __('user.name') }}</label>
                <input type="text" name="name" class="form-control" id="exampleInputName" required
                       placeholder="{{ __('user.create.enter_name') }}">
            </div>
            <div class="form-group">
                <label for="exampleInputEmail">{{ __('user.email') }}</label>
                <input type="email" name="email" class="form-control" id="exampleInputEmail" required
                       placeholder="{{ __('user.create.enter_email') }}">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword">{{ __('user.password') }}</label>
                <input type="password" name="password" class="form-control" id="exampleInputPassword" required
                       placeholder="{{ __('user.create.enter_password') }}">
            </div>
            <button type="submit" class="btn btn-primary">{{ __('html.save') }}</button>
        </form>
    </div>
@endsection

resources/views/users/edit.blade.php
@extends('master')
@section('content')
    <div class="container">
        <form action="{{ route('users.update', $user->id) }}" method="POST">
            {{ csrf_field() }}
            {{ method_field('PATCH') }}
            <div class="form-group">
                <label for="exampleInputName">{{ __('user.name') }}</label>
                <input type="text" name="name" class="form-control" id="exampleInputName" required
                       placeholder="{{ __('user.create.enter_name') }}" value="{{ $user->name }}">
            </div>
            <div class="form-group">
                <label for="exampleInputEmail">{{ __('user.email') }}</label>
                <input type="email" name="email" class="form-control" id="exampleInputEmail" required
                       placeholder="{{ __('user.create.enter_email') }}" value="{{ $user->email }}">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword">{{ __('user.password') }}</label>
                <input type="password" name="password" class="form-control" id="exampleInputPassword"
                       placeholder="{{ __('user.create.enter_password') }}">
            </div>
            <button type="submit" class="btn btn-primary">{{ __('html.save') }}</button>
        </form>
    </div>
@endsection

resources/views/users/index.blade.php
@extends('master')
@section('content')
    <div class="container">
        <div class="jumbotron">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">{{ __('user.index.table.id') }}</th>
                    <th scope="col">{{ __('user.index.table.name') }}</th>
                    <th scope="col">{{ __('user.index.table.email') }}</th>
                    <th scope="col">{{ __('html.action') }}</th>
                </tr>
                </thead>
                <tbody>
                @foreach($users as $key => $user)
                    <tr data-row-id="{{ $user->id }}">
                        <th scope="row">{{ $user->id }}</th>
                        <td> <a href="{{ route('users.edit', $user->id) }}">{{ $user->name }}</a></td>
                        <td>{{ $user->email }}</td>
                        <td>
                            <button onclick="Main.delete(this, '{{ route('users.destroy', $user->id) }}', '{{ csrf_token() }}')"
                                    type="button" class="btn btn-danger">{{ __('html.delete') }}
                            </button>
                            <a href="{{ route('users.show', $user->id) }}" type="button" class="btn btn-info">
                                {{ __('html.show') }}
                            </a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/users/show.blade.php
@extends('master')
@section('content')
    <div class="container">
        <div class="form-group">
            <label for="exampleInputName">{{ __('user.name') }}</label>
            <input type="text" name="name" class="form-control" id="exampleInputName" readonly value="{{ $user->name }}">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail">{{ __('user.email') }}</label>
            <input type="email" name="email" class="form-control" id="exampleInputEmail" readonly value="{{ $user->email }}">
        </div>
        <a type="button" class="btn btn-primary" href="{{ route('users.index') }}">{{ __('html.back') }}</a>
    </div>
@endsection